export const NFT_MINT_CONTRACT_ADDRESS = 'TWFDLeemnRJXhTEkWyER7qdqxVhW1WRKSu'
export const HOUSE_BUY_CONTRACT_ADDRESS = 'TM9Aj9JMUbozizRhVXYVkyu7a7UWPF2RPQ'
export const USDT_TESTNET_CONTRACT_ADDRESS = 'TXLAQ63Xg1NAzckPwKHvzw7CSEmLMEqcdj'